name: test_env
channels:
- conda-forge
- anaconda
dependencies:
- python=3.8.5
- numpy
- pandas
- joblib
- pip
- pip:
  - azureml-core
  - azureml-defaults  
  - statsmodels==0.11.0
  - scipy==1.5.2
  - scikit-learn==0.24.2
  - inference_schema