name: test_env
channels:
- conda-forge
- anaconda
dependencies:
- python=3.8.5
- numpy
- pandas=1.4.2
- joblib
- pip
- pip:
  - azureml-core
  - azureml-defaults  
  - statsmodels==0.11.0
  - scipy==1.5.2
  - scikit-learn==0.24.2
  - inference_schema==1.3.0
  - cloudpickle==2.1.0
  - xgboost==1.3.3